#!/usr/bin/python

import sys

if len(sys.argv) <= 1:
    print 'Usage: untab <filename>'
    exit(1)

from readable_lisp import parse, Formatter

print Formatter().format(parse(open(sys.argv[1], 'r').read()))